/** @format */
import Head from "next/head";
import React from "react";
import Accordion from "../components/Accordion";
import AccordionL from "../components/AccordionL";


export default function Home() {
    return (
        <div>
          <Head>
            <title>Responsive Accordion</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/pro.ico" />
          </Head>
          <div className="flex grid grid-row-2 md:grid-cols-2">
          <AccordionL />
          <Accordion />
          </div>
        </div>
      );
}

